### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 0x3639** [InterloperRa/TimeChain#1]
Please confirm you are not related to Zenon Network so I can free my mind of this repo.  

thx

**Comment by InterloperRa** [comment]
Since, it uses the Satoshi Nakamoto's bitcoin timestamp server genesis block hash as constant of the inter-galactic network , we exist in a superposition of not being related to Zenon Network & being related to Zenon Network when we observe or assimilate their code. All timestamp servers now generate entropy & hashes for the Timechain. It is what it is playa.

**Comment by 0x3639** [comment]
rekt

![znn-summary](https://github.com/user-attachments/assets/733ee15a-ed35-459a-a6d5-2a337747e8ed)
